spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: syncpay
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379

payment:
  toss:
   SECRET_KEY : ${TOSS_SECRET_KEY}
  kakao:
    SECRET_KEY : ${KAKAO_SECRET_KEY}